### ISSUE TITLE
Garbage-collect static K8s manifests from the repos

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#189]
Kubernetes components used to have "static manifests" as a deployment option. This is no longer supported, but the manifests are still there and the CI checks them for consistency. We should garbage-collect them and cleanup the CI.

## TODO list
- [x] Retire all the docs that has any link to the manifests
- [x] Clean [k8s-metadata-injection](https://github.com/newrelic/k8s-metadata-injection)
- [x] Clean [nri-discovery-kubernetes](https://github.com/newrelic/nri-discovery-kubernetes)
- [x] Clean [nri-kube-events](https://github.com/newrelic/nri-kube-events)
- [x] Clean [nri-kubernetes](https://github.com/newrelic/nri-kubernetes)
- [x] Clean [nri-prometheus](https://github.com/newrelic/nri-prometheus)
- [x] Clean repository unused secrets

**Comment by kang-makes** [comment]
I only can see these manifests to be cleaned.

https://github.com/newrelic/k8s-metadata-injection/tree/main/deploy
https://github.com/newrelic/nri-discovery-kubernetes/tree/master/deploy
https://github.com/newrelic/nri-kube-events/blob/main/skaffold.yaml
https://github.com/newrelic/nri-kube-events/tree/main/deploy
https://github.com/newrelic/nri-kubernetes/tree/main/deploy
https://github.com/newrelic/nri-prometheus/blob/main/skaffold.yaml
https://github.com/newrelic/nri-prometheus/blob/main/Dockerfile.dev
https://github.com/newrelic/nri-prometheus/tree/main/deploy

Am I correct?

**Comment by kang-makes** [comment]
(nri-kube-events)[https://github.com/newrelic/nri-kube-events/pull/78] has been merged.

**Comment by kang-makes** [comment]
[nri-prometheus](https://github.com/newrelic/nri-prometheus/pull/237) has been merged.
