### ISSUE TITLE
Upgrade integrations to SDK v3.6.7

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-coreint#20]
When multiple instances of an integration is running on the same host the sdk mixed metrics that uses the sdk storer (DETA, RATE, PDELTA and PRATE). This bug was fixed on the last release  [v3.6.7](https://github.com/newrelic/infra-integrations-sdk/releases/tag/3.6.7) 

This ticket has been added to track the sdk version upgrade on integrations using this metrics:
- [RATE](https://github.com/search?q=org%3Anewrelic+metric.RATE&type=code)
- [DELTA](https://github.com/search?q=org%3Anewrelic+metric.DELTA&type=code)
- [PRATE](https://github.com/search?q=org%3Anewrelic+PRATE&type=code)
- [PDELTA](https://github.com/search?q=org%3Anewrelic+PDELTA&type=code)

## Scope

TBD
- [ ] Migrate to gomod
- [ ] Bump to sdk v3.6.7
- [ ] Update CI to support go mod and bump go version
- [ ] Remove mention from govendor at the Readme
- [ ] Remove old project from `Github newrelic` snyk org and re-add it to Github coreint after merge to track the go.mod

## Useful tools

- https://github.com/oligot/go-mod-upgrade

## Pending integrations

- [x] nri-nginx
- [x] nri-snmp
- [x] nri-redis
- [x] nri-apache
- [x] nri-mysql
- [x] nri-kafka
- [x] nri-mssql
- [x] nri-oracledb
- [x] nri-elasticsearch
- [x] nri-mongodb
- [x] nri-cassandra
- [x] nri-consul
- [x] nri-couchbase
- [x] nri-f5 (⚠️ Stay in Go 1.14 or lower [nri-f5#37](https://github.com/newrelic/nri-f5/issues/37))
- [x] nri-haproxy
- [x] nri-jmx
- [x] nri-memcached
- [x] nri-nagios
- [x] nri-postgresql
- [x] nri-rabbitmq
- [x] nri-varnish
- [ ] nri-flex? (belongs to CAOS)

### Useful tools

https://github.com/oligot/go-mod-upgrade
